<?php

namespace Database\Seeders;

use App\Models\Develop\DevelopmentPrice;
use Illuminate\Database\Seeder;

class DevelopmentPriceSeeder extends Seeder
{
    /**
     * Seed the development_prices table with typical site components (blocks/modules).
     * Prices based on 2024–2025 rates: ~$35–50/h (Ukraine/EE market), simple 1–4h, complex up to 20h.
     */
    public function run(): void
    {
        $items = [
            // --- Слайдери та каруселі ---
            [
                'name' => 'Слайдер / карусель',
                'description' => 'Слайдер зображень або контенту з навігацією, автопрокруткою, адаптивністю. Налаштування в адмінці.',
                'price_frontend' => 140,
                'avg_hours_frontend' => 4,
                'price_backend' => 90,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Hero-секція (головний банер)',
                'description' => 'Великий верхній банер з заголовком, підзаголовком, CTA-кнопками, фоном або зображенням. Варіанти з відеофоном.',
                'price_frontend' => 200,
                'avg_hours_frontend' => 6,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Слайдер відгуків / testimonials',
                'description' => 'Карусель відгуків клієнтів з фото, ім’ям, посадою. Автопрокрутка, точки навігації.',
                'price_frontend' => 175,
                'avg_hours_frontend' => 5,
                'price_backend' => 105,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Слайдер «Популярні / Рекомендовані»',
                'description' => 'Горизонтальний скрол товарів або карток з кнопками «назад/вперед». Дані з API або CMS.',
                'price_frontend' => 180,
                'avg_hours_frontend' => 5,
                'price_backend' => 140,
                'avg_hours_backend' => 4,
                'currency' => 'USD',
            ],
            [
                'name' => 'Банер з таймером (акція / знижка)',
                'description' => 'Блок з зворотним відліком до дати завершення акції. Налаштування дати та тексту в адмінці.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],

            // --- Навігація та структура ---
            [
                'name' => 'Дерево категорій',
                'description' => 'Ієрархічний список категорій з вкладеними рівнями. Відображення на сайті + CRUD у адмінці.',
                'price_frontend' => 220,
                'avg_hours_frontend' => 6,
                'price_backend' => 200,
                'avg_hours_backend' => 5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Хлібні крихти (breadcrumbs)',
                'description' => 'Навігаційний ланцюжок з автоматичним формуванням з URL або структури категорій.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Випадаюче меню / мега-меню',
                'description' => 'Багаторівневе меню з dropdown або мега-меню з блоками контенту. Адаптивне бургер-меню.',
                'price_frontend' => 250,
                'avg_hours_frontend' => 7,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Header з логотипом та меню',
                'description' => 'Шапка сайту: логотип, навігація, іконки (кошик, пошук, профіль). Sticky-варіант.',
                'price_frontend' => 200,
                'avg_hours_frontend' => 6,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Footer багатоколонковий',
                'description' => 'Підвал з колонками посилань, контактами, соцмережами, копірайтом. Редагування в CMS.',
                'price_frontend' => 180,
                'avg_hours_frontend' => 5,
                'price_backend' => 90,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Навігація по сторінці (anchor menu)',
                'description' => 'Фіксоване або плаваюче меню з посиланнями на секції сторінки. Підсвітка поточної секції при скролі.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],
            [
                'name' => 'Кнопка «Наверх»',
                'description' => 'Кнопка прокрутки вгору, з’являється після певного скролу. Плавна анімація.',
                'price_frontend' => 45,
                'avg_hours_frontend' => 1.5,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],

            // --- Контентні блоки ---
            [
                'name' => 'Модульний текст (контентні блоки)',
                'description' => 'Редагувані блоки: заголовок, текст, список, цитата, код. Збір сторінки з блоків у CMS.',
                'price_frontend' => 280,
                'avg_hours_frontend' => 8,
                'price_backend' => 250,
                'avg_hours_backend' => 7,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок «Зображення + текст»',
                'description' => 'Компонент з картинкою зліва/справа та текстом. Варіанти розмітки, кнопка, посилання.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 60,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок з відео',
                'description' => 'Вставка відео (YouTube, Vimeo, своє) з обгорткою, прев’ю, відповідними пропорціями.',
                'price_frontend' => 60,
                'avg_hours_frontend' => 2,
                'price_backend' => 40,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Секція з фоновими відео',
                'description' => 'Повноекранний або обмежений блок з відео на фоні. Контроль відтворення, затемнення.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 35,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Таби / вкладки',
                'description' => 'Блок з перемиканням контенту по вкладках. Адаптивно (на мобільному — акордеон або селект).',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Акордеон (згортання блоків)',
                'description' => 'Список блоків з розгортанням/згортанням по кліку. Часто для FAQ або деталей.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 45,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок CTA (call to action)',
                'description' => 'Привертаючий блок з заголовком, текстом та кнопкою. Кольори, фон, посилання з CMS.',
                'price_frontend' => 85,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок FAQ',
                'description' => 'Питання та відповіді у вигляді акордеону або розгорнутих блоків. Редагування в адмінці.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 90,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Лічильники / статистика (цифри)',
                'description' => 'Блок з цифрами (проекти, клієнти, роки), анімація при появі в viewport.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 55,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Таймлайн / етапи',
                'description' => 'Вертикальний або горизонтальний таймлайн з кроками. Підходить для процесу, історії.',
                'price_frontend' => 160,
                'avg_hours_frontend' => 5,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сітка карток (іконка + текст)',
                'description' => 'Features / переваги: сітка карток з іконкою, заголовком, коротким текстом.',
                'price_frontend' => 130,
                'avg_hours_frontend' => 4,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Логотипи клієнтів / партнерів',
                'description' => 'Сітка або слайдер логотипів. Підсвітка при наведенні, посилання. Управління в CMS.',
                'price_frontend' => 110,
                'avg_hours_frontend' => 3.5,
                'price_backend' => 90,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Таблиця (адаптивна)',
                'description' => 'Таблиця з прокруткою на малих екранах або перетворенням у картки. Сортування опцій.',
                'price_frontend' => 140,
                'avg_hours_frontend' => 4,
                'price_backend' => 80,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Прогрес-бар',
                'description' => 'Візуалізація прогресу (навички, етапи замовлення, завантаження). Анімація заповнення.',
                'price_frontend' => 65,
                'avg_hours_frontend' => 2,
                'price_backend' => 35,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Stepper (етапи оформлення)',
                'description' => 'Візуальні кроки (наприклад, кошик → доставка → оплата). Активний крок, валідація.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],

            // --- Медіа ---
            [
                'name' => 'Галерея з lightbox',
                'description' => 'Сітка/слайдер зображень з відкриттям у повноекранному перегляді, підписи, сортування.',
                'price_frontend' => 170,
                'avg_hours_frontend' => 5,
                'price_backend' => 120,
                'avg_hours_backend' => 3.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Збільшення зображення при наведенні (zoom)',
                'description' => 'Zoom частини зображення при наведенні курсора. Типово для карток товару.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],
            [
                'name' => 'Lazy load зображень',
                'description' => 'Підвантаження зображень при скролі. Placeholder, blur, атрибути для SEO.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 25,
                'avg_hours_backend' => 0.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Паралакс-блок',
                'description' => 'Ефект паралаксу при скролі (фон рухається повільніше). Один блок або секція.',
                'price_frontend' => 130,
                'avg_hours_frontend' => 4,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],
            [
                'name' => 'Анімації при скролі',
                'description' => 'Поява елементів (fade, slide) при доскролі до секції. Налаштування тригерів.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],

            // --- Форми ---
            [
                'name' => 'Форма зворотного зв’язку',
                'description' => 'Форма з валідацією, відправкою на email або в CRM, захист від спаму (captcha/honeypot).',
                'price_frontend' => 120,
                'avg_hours_frontend' => 3.5,
                'price_backend' => 140,
                'avg_hours_backend' => 4,
                'currency' => 'USD',
            ],
            [
                'name' => 'Форма підписки на розсилку',
                'description' => 'Поле email + кнопка. Інтеграція з Mailchimp, SendPulse тощо. Збереження в БД.',
                'price_frontend' => 60,
                'avg_hours_frontend' => 2,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Завантаження файлів (upload)',
                'description' => 'Поле завантаження файлів: прев’ю, обмеження типу/розміру, прогрес, множинний вибір.',
                'price_frontend' => 130,
                'avg_hours_frontend' => 4,
                'price_backend' => 110,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Календар / вибір дати',
                'description' => 'Вибір дати (одна або діапазон). Інтеграція з формою, обмеження по датах.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 60,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Вибір часу / слотів бронювання',
                'description' => 'Вибір часу або слотів для запису. Перевірка зайнятості, блокування обраних.',
                'price_frontend' => 180,
                'avg_hours_frontend' => 6,
                'price_backend' => 220,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Pop-up / модальне вікно',
                'description' => 'Модальне вікно (форма, контент, відео). Тригери: клік, таймер, exit intent. Закриття по overlay.',
                'price_frontend' => 95,
                'avg_hours_frontend' => 3,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],

            // --- Пошук та каталог ---
            [
                'name' => 'Пошук по сайту',
                'description' => 'Поле пошуку з підказками (autocomplete), сторінка результатів, підсвітка збігів.',
                'price_frontend' => 200,
                'avg_hours_frontend' => 6,
                'price_backend' => 250,
                'avg_hours_backend' => 7,
                'currency' => 'USD',
            ],
            [
                'name' => 'Фільтри каталогу',
                'description' => 'Фільтрація по категоріях, ціні, атрибутах. Без перезавантаження сторінки (AJAX).',
                'price_frontend' => 320,
                'avg_hours_frontend' => 10,
                'price_backend' => 240,
                'avg_hours_backend' => 7,
                'currency' => 'USD',
            ],
            [
                'name' => 'Фільтр за ціною (слайдер діапазону)',
                'description' => 'Два повзунки мін/макс ціни. Синхронізація з каталогом, URL-параметри.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сортування (за ціною, назвою, новизною)',
                'description' => 'Випадаючий список або кнопки сортування. Оновлення списку без перезавантаження.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Пагінація / «Показати ще»',
                'description' => 'Пагінація або підвантаження наступних елементів (infinite scroll). Стилізація під дизайн.',
                'price_frontend' => 60,
                'avg_hours_frontend' => 2,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Розширений пошук (фільтри + збереження)',
                'description' => 'Складні фільтри з збереженням запиту, історією пошуку, експортом результатів.',
                'price_frontend' => 280,
                'avg_hours_frontend' => 9,
                'price_backend' => 320,
                'avg_hours_backend' => 9,
                'currency' => 'USD',
            ],

            // --- Карта, контакти, соцмережі ---
            [
                'name' => 'Карта (Google Maps / OpenStreetMap)',
                'description' => 'Вставка мапи з маркером або кількома точками. Можливість змінити координати в адмінці.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок контактів (телефон, email, адреса)',
                'description' => 'Секція з контактами, іконками, посиланнями (tel:, mailto:). Редагування в CMS.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 60,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Соціальні посилання / шеринг',
                'description' => 'Блок іконок соцмереж або кнопки «Поділитися». Налаштування посилань у CMS.',
                'price_frontend' => 50,
                'avg_hours_frontend' => 1.5,
                'price_backend' => 40,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],

            // --- E-commerce: товари ---
            [
                'name' => 'Картка товару (список / сітка)',
                'description' => 'Картка з фото, назвою, ціною, кнопкою «в кошик». Ховер, швидкий перегляд опцій.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сторінка товару (деталі)',
                'description' => 'Повна сторінка: галерея, опис, характеристики, варіанти (розмір, колір), ціна, кошик.',
                'price_frontend' => 350,
                'avg_hours_frontend' => 10,
                'price_backend' => 280,
                'avg_hours_backend' => 8,
                'currency' => 'USD',
            ],
            [
                'name' => 'Варіанти товару (розмір, колір)',
                'description' => 'Вибір варіанту (select або кнопки), оновлення ціни/наявності, зміна зображення.',
                'price_frontend' => 140,
                'avg_hours_frontend' => 4,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Вкладки на сторінці товару (опис, характеристики, відгуки)',
                'description' => 'Таби: опис, технічні характеристики, відгуки. Контент з CMS.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Рейтинг / зірки',
                'description' => 'Відображення рейтингу (зірки), опційно — форма голосування. Підсумок середнього.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Відгуки про товар',
                'description' => 'Список відгуків з рейтингом, датою, текстом. Форма додавання (після покупки). Модерація в адмінці.',
                'price_frontend' => 220,
                'avg_hours_frontend' => 7,
                'price_backend' => 200,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Швидкий перегляд товару (quick view)',
                'description' => 'Модальне вікно з основною інфо та кнопкою «в кошик» без переходу на сторінку товару.',
                'price_frontend' => 180,
                'avg_hours_frontend' => 6,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок «Схожі товари»',
                'description' => 'Слайдер або сітка товарів за категорією/тегами. Логіка рекомендацій на бекенді.',
                'price_frontend' => 160,
                'avg_hours_frontend' => 5,
                'price_backend' => 140,
                'avg_hours_backend' => 4,
                'currency' => 'USD',
            ],
            [
                'name' => 'Блок «Останні переглянуті»',
                'description' => 'Секція з товарами, які користувач нещодавно переглядав. Збереження в cookie/localStorage.',
                'price_frontend' => 130,
                'avg_hours_frontend' => 4,
                'price_backend' => 90,
                'avg_hours_backend' => 2.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Наявність / склад по складах',
                'description' => 'Відображення наявності по складах або «Є в наявності / під замовлення». Оновлення з БД.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 110,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Повідомлення про наявність',
                'description' => 'Форма «Повідомити, коли з’явиться» з збереженням email та відправкою після надходження.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Таблиця порівняння товарів',
                'description' => 'Сторінка порівняння: кілька товарів у стовпцях, характеристики в рядках. Додати/прибрати.',
                'price_frontend' => 300,
                'avg_hours_frontend' => 10,
                'price_backend' => 180,
                'avg_hours_backend' => 5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Цінова таблиця (pricing table)',
                'description' => 'Блок тарифів: кілька колонок з ціною, списком можливостей, кнопкою. Перемикач місяць/рік.',
                'price_frontend' => 200,
                'avg_hours_frontend' => 6,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],

            // --- Кошик та замовлення ---
            [
                'name' => 'Міні-кошик у хедері',
                'description' => 'Іконка кошика з кількістю та випадаючим списком товарів, сумою, посиланням на кошик.',
                'price_frontend' => 170,
                'avg_hours_frontend' => 5,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сторінка кошика',
                'description' => 'Список товарів з кількістю, ціною, зміною/видаленням. Підсумок, промокод, кнопка до оформлення.',
                'price_frontend' => 280,
                'avg_hours_frontend' => 9,
                'price_backend' => 250,
                'avg_hours_backend' => 7,
                'currency' => 'USD',
            ],
            [
                'name' => 'Оформлення замовлення (чекаут)',
                'description' => 'Багатокрокова форма: доставка, оплата, підсумок. Валідація, збереження чернетки.',
                'price_frontend' => 450,
                'avg_hours_frontend' => 14,
                'price_backend' => 400,
                'avg_hours_backend' => 12,
                'currency' => 'USD',
            ],
            [
                'name' => 'Промокод / знижка',
                'description' => 'Поле введення промокоду, перевірка на бекенді, застосування знижки до суми замовлення.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Калькулятор доставки',
                'description' => 'Вибір регіону/відділення, розрахунок вартості та термінів доставки (Нова пошта, інші).',
                'price_frontend' => 180,
                'avg_hours_frontend' => 6,
                'price_backend' => 220,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сторінка «Дякуємо» після замовлення',
                'description' => 'Екран підтвердження замовлення з номером, деталями, посиланням на трекінг.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 70,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Трекінг замовлення',
                'description' => 'Сторінка статусу замовлення за номером. Етапи виконання, посилання на доставку.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 200,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],

            // --- Обране, порівняння, кабінет ---
            [
                'name' => 'Обране / wishlist',
                'description' => 'Збереження товарів в обране (іконка серця), сторінка обраного, синхронізація з акаунтом.',
                'price_frontend' => 160,
                'avg_hours_frontend' => 5,
                'price_backend' => 140,
                'avg_hours_backend' => 4,
                'currency' => 'USD',
            ],
            [
                'name' => 'Авторизація / реєстрація',
                'description' => 'Форми логіну та реєстрації. Відновлення пароля, опційно OAuth (Google, Facebook).',
                'price_frontend' => 220,
                'avg_hours_frontend' => 7,
                'price_backend' => 280,
                'avg_hours_backend' => 8,
                'currency' => 'USD',
            ],
            [
                'name' => 'Кабінет користувача (профіль)',
                'description' => 'Сторінка профілю: особисті дані, зміна пароля, адреси доставки. Редагування та збереження.',
                'price_frontend' => 250,
                'avg_hours_frontend' => 8,
                'price_backend' => 220,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Історія замовлень',
                'description' => 'Список замовлень користувача з деталями, статусом, повторним замовленням.',
                'price_frontend' => 200,
                'avg_hours_frontend' => 6,
                'price_backend' => 180,
                'avg_hours_backend' => 5,
                'currency' => 'USD',
            ],

            // --- Блог ---
            [
                'name' => 'Список статей блогу',
                'description' => 'Сітка/список карток статей з зображенням, заголовком, датою, автором, уривком. Пагінація.',
                'price_frontend' => 180,
                'avg_hours_frontend' => 6,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сторінка статті блогу',
                'description' => 'Повна стаття: заголовок, дата, автор, контент (HTML/rich text), соцшеринг, теги, коментарі.',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Коментарі до статті',
                'description' => 'Вкладені коментарі, форма додавання, модерація в адмінці, нотифікації.',
                'price_frontend' => 220,
                'avg_hours_frontend' => 7,
                'price_backend' => 200,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Теги / хмара тегів',
                'description' => 'Хмара тегів або список тегів з посиланнями на фільтрацію контенту. Управління в CMS.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Архів блогу по датах / категоріях',
                'description' => 'Сайдбар або сторінка з архівом по місяцях або категоріях статей.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 100,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],

            // --- Користуцький досвід ---
            [
                'name' => 'Тултипи',
                'description' => 'Підказки при наведенні або фокусі. Універсальний компонент для форм та інтерфейсу.',
                'price_frontend' => 55,
                'avg_hours_frontend' => 1.5,
                'price_backend' => 25,
                'avg_hours_backend' => 0.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Нотифікації / тости',
                'description' => 'Сповіщення про успіх/помилку після дій. Автозникнення, черга повідомлень.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Drag-and-drop сортування',
                'description' => 'Перетягування елементів для зміни порядку (наприклад, в адмінці або в списку).',
                'price_frontend' => 150,
                'avg_hours_frontend' => 5,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'Банер cookie / згода на cookies',
                'description' => 'Повідомлення про cookies з кнопкою прийняття, збереження вибору, посилання на політику.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 50,
                'avg_hours_backend' => 1.5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Мультимовність (перемикач мови)',
                'description' => 'Перемикач мови в хедері, збереження вибору, підстановка перекладів з БД/файлів.',
                'price_frontend' => 120,
                'avg_hours_frontend' => 4,
                'price_backend' => 200,
                'avg_hours_backend' => 6,
                'currency' => 'USD',
            ],
            [
                'name' => 'Темна тема / перемикач теми',
                'description' => 'Перемикач світло/темна тема. Збереження в localStorage, підтримка системних налаштувань.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 30,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Сторінка 404',
                'description' => 'Кастомна сторінка «Не знайдено» з посиланням на головну та пошуком.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 30,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Sitemap (HTML)',
                'description' => 'Сторінка з картою сайту — посилання на основні розділи. Опційно XML sitemap для SEO.',
                'price_frontend' => 60,
                'avg_hours_frontend' => 2,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Експорт у PDF / Excel',
                'description' => 'Кнопка експорту таблиці або контенту в PDF або Excel. Налаштування полів.',
                'price_frontend' => 90,
                'avg_hours_frontend' => 3,
                'price_backend' => 150,
                'avg_hours_backend' => 4,
                'currency' => 'USD',
            ],
            [
                'name' => 'Друк сторінки',
                'description' => 'Стилі для друку (приховування меню, реклами), кнопка «Друкувати».',
                'price_frontend' => 50,
                'avg_hours_frontend' => 1.5,
                'price_backend' => 0,
                'avg_hours_backend' => null,
                'currency' => 'USD',
            ],

            // --- Інтеграції та віджети ---
            [
                'name' => 'Онлайн-чат віджет',
                'description' => 'Інтеграція чату (Crisp, Intercom, Jivo тощо): віджет, налаштування, події.',
                'price_frontend' => 60,
                'avg_hours_frontend' => 2,
                'price_backend' => 40,
                'avg_hours_backend' => 1,
                'currency' => 'USD',
            ],
            [
                'name' => 'Калькулятор (наприклад вартості)',
                'description' => 'Інтерактивний калькулятор: поля вводу, формула, динамічний результат. Налаштування в адмінці.',
                'price_frontend' => 250,
                'avg_hours_frontend' => 8,
                'price_backend' => 180,
                'avg_hours_backend' => 5,
                'currency' => 'USD',
            ],
            [
                'name' => 'Віджет погоди',
                'description' => 'Блок з поточною погодою за містом. Інтеграція з API погоди.',
                'price_frontend' => 100,
                'avg_hours_frontend' => 3,
                'price_backend' => 80,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
            [
                'name' => 'Курс валют',
                'description' => 'Відображення курсу валют (НБУ або інше джерело). Оновлення по розкладу або вручну.',
                'price_frontend' => 80,
                'avg_hours_frontend' => 2.5,
                'price_backend' => 120,
                'avg_hours_backend' => 3,
                'currency' => 'USD',
            ],
            [
                'name' => 'RSS-стрічка',
                'description' => 'Посилання на RSS та віджет останніх записів з іншого джерела.',
                'price_frontend' => 70,
                'avg_hours_frontend' => 2,
                'price_backend' => 90,
                'avg_hours_backend' => 2,
                'currency' => 'USD',
            ],
        ];

        foreach ($items as $item) {
            DevelopmentPrice::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
