import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import preset from './vendor/filament/support/tailwind.config.preset'

export default {
    presets: [preset],
    content: [
        './app/Filament/**/*.php',
        './resources/views/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [forms],
    safelist: [
        // Gradient classes for our custom components
        'from-blue-50',
        'to-indigo-50',
        'from-blue-900/20',
        'to-indigo-900/20',
        'from-amber-50',
        'to-orange-50',
        'from-amber-900/20',
        'to-orange-900/20',
        // Background colors
        'bg-blue-50',
        'bg-green-50',
        'bg-purple-50',
        'bg-amber-50',
        'bg-blue-900/20',
        'bg-green-900/20',
        'bg-purple-900/20',
        'bg-amber-900/20',
        // Border colors
        'border-blue-200',
        'border-green-200',
        'border-purple-200',
        'border-amber-200',
        'border-orange-200',
        'border-blue-800',
        'border-green-800',
        'border-purple-800',
        'border-amber-800',
        'border-orange-800',
        // Text colors
        'text-blue-800',
        'text-green-800',
        'text-purple-800',
        'text-amber-800',
        'text-orange-800',
        'text-blue-200',
        'text-green-200',
        'text-purple-200',
        'text-amber-200',
        'text-orange-200',
        'text-blue-600',
        'text-green-600',
        'text-purple-600',
        'text-amber-600',
        'text-orange-600',
        'text-blue-300',
        'text-green-300',
        'text-purple-300',
        'text-amber-300',
        'text-orange-300',
        'text-blue-400',
        'text-green-400',
        'text-emerald-400',
        'text-emerald-600',
        'text-amber-400',
        // Progress bar colors
        'bg-emerald-500',
        'bg-amber-500',
        'bg-blue-500',
        'bg-gray-500',
        // Rounded and spacing
        'rounded-xl',
        'rounded-lg',
        'p-6',
        'p-4',
        'p-3',
        'gap-4',
        'gap-1',
        'mb-1',
        'mb-2',
        'mt-1',
        'mt-3',
        'mt-4',
        // Grid and flex
        'grid-cols-1',
        'grid-cols-2',
        'grid-cols-4',
        'md:grid-cols-2',
        'md:grid-cols-4',
        'lg:grid-cols-4',
        // Font weights
        'font-bold',
        'font-medium',
        // Text sizes
        'text-xs',
        'text-sm',
        'text-2xl',
        'text-3xl',
        'text-4xl',
        // Width and height
        'w-3',
        'h-3',
        'h-2',
        // Position and display
        'overflow-hidden',
        'text-center',
        'justify-center',
        'items-center',
        'flex-wrap',
    ],
};